config/routes.rb
Rails.application.routes.draw do

  
  get '/logout' => 'sessions#destroy', as: :logout
  get '/login'  => 'sessions#index',   as: :login
  post '/login' => 'sessions#create'
  get '/register' => 'users#register',      as: :register
  post '/register' => 'users#create'

  resources :users do
    member do
      get 'activate'
    end
  end

  resources :categories

  resources :questions do
    collection do
      get 'answered'
      get 'not_answered'
    end
    resources :answers
  end

  root 'questions#index'
  
  get '/permission_denied' => 'home#permission_denied', as: :permission_denied
  get '/wait_for_activation' => 'home#wait_for_activation', as: :wait_for_activation

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user.rb
class User < ActiveRecord::Base
  STATUS = ["Newbie", "User", "Trusted", "VIP"]
  ROLE   = ["user", "admin"]
  
  validates :email, presence: true, uniqueness: true
  
  has_secure_password
  
  has_many :questions
  has_many :answers
  
  def admin?
    self.role == "admin"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:register, :create]
  skip_before_action :check_if_user_active, only: [:register, :create]
  before_action :check_if_admin, except: [:register, :create]
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  
  def index
    @users = User.order("created_at desc")
    @questions = Question.all
  end
  
  def show
  end

  def register
    @user = User.new
  end
  
  def new
    @user = User.new
  end

  def edit
  end
  
  def create
    @user = User.new(user_params)

    if @user.save
      if current_user
        redirect_to users_path
      else
        login(@user)
        
        redirect_to root_path
      end
    else
      if current_user
        render :new
      else
        flash[:alert] = "Email already has been taken."
        redirect_to :back
      end
    end
  end
  
  def update
    if @user.update(user_params)
      redirect_to users_path
    else
      render :edit
    end
  end
  
  def destroy
    @user.destroy
    
    redirect_to users_path
  end

  def activate
    user = User.find(params[:id])
    user.update_column(:active, true)
    
    redirect_to :back
  end
  
  private
  
    def set_user
      @user = User.find(params[:id])
    end
  
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :role, :active, :status)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div class="alert">
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name, placeholder: "Name", class: "form-control width-80", autofocus: true %>
  </div>
  <div class="field">
    <%= f.text_field :email, placeholder: "Email", class: "form-control width-80" %>
  </div>
  <div class="field">
    <%= f.password_field :password, placeholder: "Password", class: "form-control width-80" %>
  </div>
  <div>
    <%= f.password_field :password_confirmation, placeholder: "Password confirmation", class: "form-control width-80" %>
  </div>
  <div class="field">
    <%= f.select :role, User::ROLE, {}, {class: "form-control width-80"} %>
  </div>
  <div class="form-control width-80">
    <%= f.check_box :active %> Active
  </div>
  <div class="field">
    <%= f.select :status, User::STATUS, {}, {class: "form-control width-80"} %>
  </div>
  <div class="actions">
    <%= f.submit nil, class: "btn btn-default width-80" %>
  </div>
<% end %>

app/views/users/_info.html.erb
<div class="user-info">
  <% if current_user %>
    <br>
    <br>
    <h2>User: <%= current_user.name %></h2>
    <h5>User status: <%= current_user.status %></h5>
    <h5>Account status: <%= current_user.active ? "Activated" : "Waiting for activation" %></h5>
    <%= link_to "Log out", logout_path %> 
  <% end %>
</div>

app/views/users/_reg_form.html.erb
<div class="col-md-offset-3 col-md-6">
  <%= form_for(@user) do |f| %>
    <div>
      <%= f.text_field :name, placeholder: "Name", class: "form-control width-80", autofocus: true %>
    </div>

    <div>
      <%= f.email_field :email, placeholder: "Email", class: "form-control width-80"%>
    </div>

    <div>
      <%= f.password_field :password, placeholder: "Password", class: "form-control width-80", autocomplete: "off" %>
    </div>

    <div>
      <%= f.password_field :password_confirmation, placeholder: "Password confirmation", class: "form-control width-80", autocomplete: "off" %>
    </div>

    <div>
      <%= f.submit "Sign up", class: "btn btn-default width-80" %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="col-md-offset-3 col-md-6">
  <h2 style="text-align: center">Edit user</h2>
  <%= render 'form' %>
</div>

app/views/users/index.html.erb
<br>
<%= link_to "New User", new_user_path, class: "btn btn-success" %>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Answered questions</th>
      <th>Role</th>
      <th>Status</th>
      <th>Activation</th>
      <th colspan="2">Management</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= "#{user.answers.count} / #{@questions.count}" %></td>
        <td><%= user.role %></td>
        <td><%= user.status %></td>
        <td><%= user.active? ? ("Activated") : (link_to 'Activate', activate_user_path(user))  %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<div class="col-md-offset-3 col-md-6">
  <h2 style="text-align: center">New user</h2>
  <%= render 'form' %>
</div>

app/views/users/register.html.erb
<%= render 'reg_form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<% unless current_user.active? %>
  <h2>Please wait for activation!</h2>
<% end %>

<% if current_user.active? %>
  <p>
    <strong>Name:</strong>
    <%= @user.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @user.email %>
  </p>

  <p>
    <strong>Role:</strong>
    <%= @user.role %>
  </p>

  <p>
    <strong>Active:</strong>
    <%= @user.active %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= @user.status %>
  </p>

  <%= link_to 'Edit', edit_user_path(@user) %> |
  <%= link_to 'Back', users_path %>
<% end %>