config/routes.rb
Rails.application.routes.draw do

  
  get '/logout' => 'sessions#destroy', as: :logout
  get '/login'  => 'sessions#index',   as: :login
  post '/login' => 'sessions#create'
  get '/register' => 'users#register',      as: :register
  post '/register' => 'users#create'

  resources :users do
    member do
      get 'activate'
    end
  end

  resources :categories

  resources :questions do
    collection do
      get 'answered'
      get 'not_answered'
    end
    resources :answers
  end

  root 'questions#index'
  
  get '/permission_denied' => 'home#permission_denied', as: :permission_denied
  get '/wait_for_activation' => 'home#wait_for_activation', as: :wait_for_activation

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :check_if_user_active
  
  def index
  end
  
  def permission_denied
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_navigation.html.erb
<% unless current_user %>
  <div class="col-md-offset-3 col-md-6">
    <ul class="nav nav-tabs authentication">
      <li class="item"><%= link_to "Register", register_path %></li>
      <li class="item"><%= link_to "Log In", login_path %></li>
    </ul>
  </div>
<% end %>

<% if current_user && current_user.admin? %>
  <div class="col-md-offset-3 col-md-6">
    <ul class="nav nav-tabs admin">
      <li class="item"><%= link_to "Users", users_path %></li>
      <li class="item"><%= link_to "Questions", questions_path %></li>
      <li class="item"><%= link_to "Categories", categories_path %></li>
    </ul>
  </div>
  <br>
  <br>
<% end %>

<% if current_user && !current_user.admin? && current_user.active?%>
  <div class="col-md-offset-3 col-md-6">
    <ul class="nav nav-tabs admin">
      <li class="item"><%= link_to "All Q", questions_path %></li>
      <li class="item"><%= link_to "Answered", answered_questions_path %></li>
      <li class="item"><%= link_to "Pending", not_answered_questions_path %></li>
    </ul>
  </div>
  <br>
  <br>
<% end %>

app/views/home/index.html.erb
<h1>Questions and answers</h1>
<p>Welcome</p>

app/views/home/permission_denied.html.erb
<h1>You don't have access to this page.</h1>
<%= link_to "Home", root_path %>

app/views/home/wait_for_activation.html.erb
<h2>Please wait for activation.</h2>