config/routes.rb
Rails.application.routes.draw do

  
  get '/logout' => 'sessions#destroy', as: :logout
  get '/login'  => 'sessions#index',   as: :login
  post '/login' => 'sessions#create'
  get '/register' => 'users#register',      as: :register
  post '/register' => 'users#create'

  resources :users do
    member do
      get 'activate'
    end
  end

  resources :categories

  resources :questions do
    collection do
      get 'answered'
      get 'not_answered'
    end
    resources :answers
  end

  root 'questions#index'
  
  get '/permission_denied' => 'home#permission_denied', as: :permission_denied
  get '/wait_for_activation' => 'home#wait_for_activation', as: :wait_for_activation

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  validates :body, presence: true
  
  belongs_to :question
  belongs_to :user
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  
  def new
    @answer = Answer.new
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.build(answer_params)
    @answer.user = current_user
        
      if @answer.save
        redirect_to :back
      else
        flash[:alert] = "Enter your answer please."
        
        redirect_to :back
      end
    
  end

  private
  
    def answer_params
      params.require(:answer).permit(:body)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= form_for [@question, @answer] do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/_mini_form.html.erb
<%= form_tag(question_answers_path(question), method: :post, class: "form-inline") do %>
  <%= text_field_tag "answer[body]", nil, placeholder: "Type your answer", class: "form-control width-50" %>
  <%= submit_tag "Answer", class: "btn btn-success" %>
<% end %>

app/views/answers/_show_quick_answer.html.erb
<%= question.find_answer_by(current_user).first.body %>

app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<h1>Listing answers</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.body %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p>
  <strong>Body:</strong>
  <%= @answer.body %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>